// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recipes.Adapters.Postgresql;

#nullable disable

namespace Recipes.Adapters.Postgresql.Migrations
{
    [DbContext(typeof(RecipeRepository))]
    [Migration("20260608150146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cookbook")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recipes.Domain.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("recipes", "cookbook");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Description = "Классический украинский борщ со свёклой, капустой и томатной пастой. Подаётся со сметаной и чесночными пампушками.",
                            Title = "Борщ"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Description = "Традиционный новогодний салат с варёными овощами, колбасой, яйцами и майонезом.",
                            Title = "Оливье"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Description = "Домашние пельмени из пресного теста с начинкой из смешанного фарша свинины и говядины.",
                            Title = "Пельмени"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Description = "Тонкие русские блины на молоке. Подаются со сметаной, вареньем или икрой.",
                            Title = "Блины"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Description = "Куриное филе, фаршированное сливочным маслом с зеленью, в хрустящей панировке.",
                            Title = "Котлеты по-киевски"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            Description = "Густой кисло-солёный суп с мясным ассорти, солёными огурцами, оливками и лимоном.",
                            Title = "Солянка"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            Description = "Маринованная свинина на углях. Маринад — лук, уксус, специи. Подаётся с лавашом и свежими овощами.",
                            Title = "Шашлык"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            Description = "Холодный суп на квасе с варёными овощами, яйцами, колбасой и свежими огурцами.",
                            Title = "Окрошка"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000009"),
                            Description = "Узбекский плов из баранины с рисом, морковью и луком, приготовленный в казане на открытом огне.",
                            Title = "Плов"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000010"),
                            Description = "Многослойный торт из тонких медовых коржей со сметанным кремом. Настаивается не менее 8 часов.",
                            Title = "Медовик"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
