// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recipes.Adapters.Postgresql;

#nullable disable

namespace Recipes.Adapters.Postgresql.Migrations;

[DbContext(typeof(RecipeRepository))]
[Migration("20260613102202_AddIngredients")]
partial class AddIngredients
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("cookbook")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Recipes.Domain.Ingredient", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("category");

                b.Property<float>("DefaultAmount")
                    .HasColumnType("real")
                    .HasColumnName("default_amount");

                b.Property<bool>("IsSystem")
                    .HasColumnType("boolean")
                    .HasColumnName("is_system");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("title");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("unit");

                b.HasKey("Id");

                b.ToTable("ingredients", "cookbook");
            });

        modelBuilder.Entity("Recipes.Domain.Recipe", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("CookingTime")
                    .HasColumnType("integer")
                    .HasColumnName("cooking_time");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)")
                    .HasColumnName("description");

                b.Property<string>("Difficulty")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("difficulty");

                b.Property<string>("Instructions")
                    .IsRequired()
                    .HasMaxLength(10000)
                    .HasColumnType("character varying(10000)")
                    .HasColumnName("instructions");

                b.Property<int>("Servings")
                    .HasColumnType("integer")
                    .HasColumnName("servings");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("title");

                b.HasKey("Id");

                b.ToTable("recipes", "cookbook");
            });
#pragma warning restore 612, 618
    }
}
