// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recipes.Adapters.Postgresql;

#nullable disable

namespace Recipes.Adapters.Postgresql.Migrations;

[DbContext(typeof(RecipeRepository))]
partial class RecipeRepositoryModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("cookbook")
            .HasAnnotation("ProductVersion", "9.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Recipes.Domain.Recipe", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("CookingTime")
                    .HasColumnType("integer")
                    .HasColumnName("cooking_time");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)")
                    .HasColumnName("description");

                b.Property<string>("Difficulty")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("difficulty");

                b.Property<string>("Instructions")
                    .IsRequired()
                    .HasMaxLength(10000)
                    .HasColumnType("character varying(10000)")
                    .HasColumnName("instructions");

                b.Property<int>("Servings")
                    .HasColumnType("integer")
                    .HasColumnName("servings");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("title");

                b.HasKey("Id");

                b.ToTable("recipes", "cookbook");

                b.HasData(
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000001"),
                        CookingTime = 120,
                        Description = "Классический украинский борщ со свёклой, капустой и томатной пастой. Подаётся со сметаной и чесночными пампушками.",
                        Difficulty = "everyday",
                        Instructions = "1. Сварить мясной бульон.\n2. Обжарить свёклу с томатной пастой.\n3. Добавить капусту и картофель.\n4. Соединить с бульоном, варить 20 минут.\n5. Подавать со сметаной.",
                        Servings = 6,
                        Title = "Борщ"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000002"),
                        CookingTime = 40,
                        Description = "Традиционный новогодний салат с варёными овощами, колбасой, яйцами и майонезом.",
                        Difficulty = "easy",
                        Instructions = "1. Отварить картофель, морковь, яйца.\n2. Нарезать кубиками все ингредиенты.\n3. Добавить горошек и колбасу.\n4. Заправить майонезом, посолить.",
                        Servings = 8,
                        Title = "Оливье"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000003"),
                        CookingTime = 90,
                        Description = "Домашние пельмени из пресного теста с начинкой из смешанного фарша свинины и говядины.",
                        Difficulty = "everyday",
                        Instructions = "1. Замесить крутое тесто из муки, яйца и воды.\n2. Смешать фарш свинины и говядины с луком.\n3. Раскатать тесто, вырезать кружки.\n4. Слепить пельмени.\n5. Варить в подсоленной воде 7–8 минут.",
                        Servings = 4,
                        Title = "Пельмени"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000004"),
                        CookingTime = 30,
                        Description = "Тонкие русские блины на молоке. Подаются со сметаной, вареньем или икрой.",
                        Difficulty = "easy",
                        Instructions = "1. Смешать яйца, молоко, муку, соль и сахар.\n2. Добавить растопленное масло.\n3. Жарить на раскалённой сковороде с двух сторон.\n4. Подавать горячими.",
                        Servings = 4,
                        Title = "Блины"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000005"),
                        CookingTime = 50,
                        Description = "Куриное филе, фаршированное сливочным маслом с зеленью, в хрустящей панировке.",
                        Difficulty = "festive",
                        Instructions = "1. Отбить куриное филе.\n2. Завернуть кусочек сливочного масла с зеленью.\n3. Обвалять в муке, яйце и панировочных сухарях.\n4. Жарить во фритюре 12–15 минут.",
                        Servings = 2,
                        Title = "Котлеты по-киевски"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000006"),
                        CookingTime = 60,
                        Description = "Густой кисло-солёный суп с мясным ассорти, солёными огурцами, оливками и лимоном.",
                        Difficulty = "everyday",
                        Instructions = "1. Обжарить мясное ассорти.\n2. Добавить лук, томатную пасту.\n3. Влить бульон, добавить солёные огурцы.\n4. Варить 20 минут.\n5. Подавать с оливками и лимоном.",
                        Servings = 6,
                        Title = "Солянка"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000007"),
                        CookingTime = 180,
                        Description = "Маринованная свинина на углях. Маринад — лук, уксус, специи. Подаётся с лавашом и свежими овощами.",
                        Difficulty = "everyday",
                        Instructions = "1. Нарезать свинину кусками 4–5 см.\n2. Замариновать с луком, уксусом и специями на 3–4 часа.\n3. Нанизать на шампуры.\n4. Жарить на углях 20–25 минут, переворачивая.",
                        Servings = 6,
                        Title = "Шашлык"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000008"),
                        CookingTime = 30,
                        Description = "Холодный суп на квасе с варёными овощами, яйцами, колбасой и свежими огурцами.",
                        Difficulty = "easy",
                        Instructions = "1. Нарезать кубиками картофель, яйца, колбасу, огурцы.\n2. Добавить зелёный лук и укроп.\n3. Залить холодным квасом.\n4. Посолить, добавить сметану по вкусу.",
                        Servings = 4,
                        Title = "Окрошка"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000009"),
                        CookingTime = 150,
                        Description = "Узбекский плов из баранины с рисом, морковью и луком, приготовленный в казане на открытом огне.",
                        Difficulty = "restaurant",
                        Instructions = "1. Раскалить масло в казане.\n2. Обжарить лук и баранину.\n3. Добавить морковь, специи (зира, барбарис).\n4. Залить водой, тушить 40 минут.\n5. Засыпать промытый рис, варить под крышкой 25 минут.",
                        Servings = 8,
                        Title = "Плов"
                    },
                    new
                    {
                        Id = new Guid("11111111-0000-0000-0000-000000000010"),
                        CookingTime = 120,
                        Description = "Многослойный торт из тонких медовых коржей со сметанным кремом. Настаивается не менее 8 часов.",
                        Difficulty = "festive",
                        Instructions = "1. Растопить мёд с маслом и сахаром на водяной бане.\n2. Добавить яйца и соду, перемешать.\n3. Всыпать муку, замесить тесто.\n4. Раскатать и выпечь 8–10 коржей.\n5. Промазать сметанным кремом, дать настояться.",
                        Servings = 10,
                        Title = "Медовик"
                    });
            });
#pragma warning restore 612, 618
    }
}
